#! /bin/bash

scripts/clean

set -x

rm -vr .venv

python3.11 -m venv .venv
source .venv/bin/activate

pip install -U pip
pip install -r requirements.txt

pip install -r requirements-dev.txt

pip install -e .
