#! /bin/bash

rm -vr .venv
rm -vr .*_cache

set -x

python3.11 -m venv .venv
source .venv/bin/activate

pip install -U pip
pip install -r requirements.txt

pip install -r requirements-dev.txt

pip install -e .
